/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  114: {
    YourContract: {
      address: "0x6A3c3B82E95f010C4bc63A7a378b2233dF6bB737",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "walletAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "reviewIndex",
              type: "uint256",
            },
          ],
          name: "ReviewAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "walletAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "ReviewsDeleted",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_walletAddress",
              type: "address",
            },
          ],
          name: "deleteReviews",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_walletAddress",
              type: "address",
            },
          ],
          name: "getReviewCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_walletAddress",
              type: "address",
            },
          ],
          name: "getReviews",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "platformName",
                  type: "string",
                },
                {
                  internalType: "uint16",
                  name: "starRating",
                  type: "uint16",
                },
                {
                  internalType: "uint256",
                  name: "numberOfReviews",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "ageOfAccount",
                  type: "uint256",
                },
                {
                  internalType: "string",
                  name: "accountName",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "pictureId",
                  type: "string",
                },
              ],
              internalType: "struct YourContract.Review[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_walletAddress",
              type: "address",
            },
            {
              internalType: "string",
              name: "_platformName",
              type: "string",
            },
            {
              internalType: "uint16",
              name: "_starRating",
              type: "uint16",
            },
            {
              internalType: "uint256",
              name: "_numberOfReviews",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_ageOfAccount",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "_accountName",
              type: "string",
            },
            {
              internalType: "string",
              name: "_pictureId",
              type: "string",
            },
          ],
          name: "writeReview",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
